"""Added fk user and 0authaccount

Revision ID: a578a358a220
Revises: 9e71bb34c792
Create Date: 2023-11-15 23:29:23.118845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a578a358a220'
down_revision: Union[str, None] = '9e71bb34c792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_account', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'oauth_account', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_account', type_='foreignkey')
    op.drop_column('oauth_account', 'user_id')
    # ### end Alembic commands ###
