import os

from dotenv import load_dotenv

load_dotenv()

DB_HOST = os.environ.get("DB_HOST")
DB_PORT = os.environ.get("DB_PORT")
DB_NAME = os.environ.get("DB_NAME")
DB_USER = os.environ.get("DB_USER")
DB_PASS = os.environ.get("DB_PASS")

#0auth
SECRET = os.environ.get("SECRET")

GOOGLE_CLIENT_ID = str(os.environ.get("GOOGLE_CLIENT_ID"))

GOOGLE_CLIENT_SECRET = str(os.environ.get("GOOGLE_CLIENT_SECRET"))

#Google mail sender API
MAIL_HOST = os.environ.get("MAIL_HOST")
MAIL_EMAIL = os.environ.get("MAIL_EMAIL")
MAIL_PASSWORD = os.environ.get("MAIL_PASSWORD")
MAIL_PORT = os.environ.get("MAIL_PORT")

#Binance and other similar API
CURRENCY_URL = str(os.environ.get("CURRENCY_URL"))
USD_PRICES_URI = str(os.environ.get("USD_PRICES_URI"))
BINANCE_WEBSOCKET_URL = str(os.environ.get("BINANCE_WEBSOCKET_URL"))
BINANCE_WEBSOCKET_ALL_COINS_URL = str(os.environ.get("BINANCE_WEBSOCKET_ALL_COINS_URL"))

RS_HOST = str(os.environ.get("RS_HOST"))
RS_PORT = str(os.environ.get("RS_PORT"))
RS_USER = str(os.environ.get("RS_USER"))
RS_PASS = str(os.environ.get("RS_PASS"))


CURRENCY_CACHE_TIME = str(os.environ.get("CURRENCY_CACHE_TIME"))

BINANCE_USDT_PAIRS_LIST = [
    "DASHUSDT", "MAGICUSDT", "OGUSDT", "TRXUSDT", "CREAMUSDT", "HIVEUSDT", "AGLDUSDT",
    "ACHUSDT", "SKLUSDT", "SEIUSDT", "BELUSDT", "ETHUPUSDT", "IDEXUSDT", "LDOUSDT", "CHESSUSDT",
    "DARUSDT", "EURUSDT", "ENSUSDT", "NMRUSDT", "WAVESUSDT", "NEARUSDT", "KDAUSDT", "ELFUSDT",
    "TIAUSDT", "FIROUSDT", "ETHDOWNUSDT", "RADU", "HIFIUSDT", "CVCUSDT", "WRXUSDT", "IOTXUSDT",
    "AVAXUSDT", "HBARUSDT", "LSK", "MULTI", "IOTA", "ZRXUSDT", "RSRUSDT", "GNOUSDT",
    "UNIUSDT", "ASTRUSDT", "WLD", "ARKM", "JOEUSDT", "COTIUSDT", "KEYUSDT", "OMUSDT",
    "QTUMUSDT", "NULSUSDT", "TRY", "WING", "IRISUSDT", "LITUSDT", "BETAUSDT", "HIGHUSDT",
    "VGXUSDT", "ORDIUSDT", "LEVERUSDT", "GMTUSDT", "DOGEUSDT", "PNTUSDT", "SYNUSDT", "SUPERUSDT",
    "ACEUSDT", "OXTUSDT", "MATICUSDT", "USDTNGN", "ERNUSDT", "MKRUSDT", "MEMEUSDT", "FXSUSDT",
    "ORNUSDT", "IQUSDT", "ENJUSDT", "XVSUSDT", "APEUSDT", "STGUSDT", "LQTYUSDT", "ALPHAUSDT",
    "FARMUSDT", "MOVRUSDT", "ALCXUSDT", "GRTUSDT", "OAXUSDT", "TKOUSDT", "BADGERUSDT", "ONEUSDT",
    "RVNUSDT", "PAXGUSDT", "SANTOSUSDT", "EDUUSDT", "DUSKUSDT", "LINAUSDT", "DOCKUSDT", "MDTUSDT",
    "XEMUSDT", "STPTUSDT", "ARDRUSDT", "BCHUSDT", "FDUSDUSDT", "REEFUSDT", "OGNUSDT", "ICXUSDT",
    "FLMUSDT", "DOTUSDT", "DYDXUSDT", "WNXMUSDT", "FORTHUSDT", "HFTUSDT", "USDTARS", "AMPUSDT",
    "VIDTUSDT", "PYRUSDT", "MBLUSDT", "TLMUSDT", "BNXUSDT", "MBOXUSDT", "CELRUSDT", "BNBUPUSDT",
    "JUVUSDT", "CLVUSDT", "1INCHUSDT", "PHAUSDT", "AUCTIONUSDT", "VIBUSDT", "USDTRON", "ACAUSDT",
    "HOOKUSDT", "BALUSDT", "QUICKUSDT", "BTCDOWNUSDT", "OPUSDT", "CTXCUSDT", "SYSUSDT", "XMRUSDT",
    "WINUSDT", "COSUSDT", "POLSUSDT", "RENUSDT", "PONDUSDT", "LINKUSDT", "RAYUSDT", "NEXOUSDT",
    "SSVUSDT", "WBTCUSDT", "DIAUSDT", "BEAMXUSDT", "WBETHUSDT", "FLOWUSDT", "CRVUSDT", "THETAUSDT",
    "UTKUSDT", "VTHOUSDT", "FLUXUSDT", "GLMRUSDT", "SCRTUSDT", "USDTZAR", "PERPUSDT", "PIVXUSDT",
    "USDTIDRT", "ARBUSDT", "FORUSDT", "DENTUSDT", "SHIBUSDT", "MDXUSDT", "PSGUSDT", "CFXUSDT",
    "ICPUSDT", "CTKUSDT", "FETUSDT", "SUSHIUSDT", "FILUSDT", "API3USDT", "NTRNUSDT", "VANRYUSDT",
    "RNDRUSDT", "BAKEUSDT", "ALPINEUSDT", "SFPUSDT", "SNXUSDT", "PROSUSDT", "STEEMUSDT", "BICOUSDT",
    "USDPUSDT", "FUNUSDT", "FLOKIUSDT", "DATAUSDT", "NEOUSDT", "STXUSDT", "GMXUSDT", "LOOMUSDT",
    "CELOUSDT", "KP3RUSDT", "GTCUSDT", "BTTCUSDT", "LTCUSDT", "PUNDIXUSDT", "IMXUSDT", "DFUSDT",
    "SCUSDT", "USDTDAI", "LPTUSDT", "GNSUSDT", "FIDAUSDT", "RDNTUSDT", "ANKRUSDT", "BANDUSDT",
    "TUSDUSDT", "OSMOUSDT", "RUNEUSDT", "CVXUSDT", "GALAUSDT", "DGBUSDT", "HARDUSDT", "KNCUSDT",
    "PEOPLEUSDT", "EPXUSDT", "ONGUSDT", "GHSTUSDT", "MTLUSDT", "GLMUSDT", "POWRUSDT", "ATMUSDT",
    "TWTUSDT", "LAZIOUSDT", "CHZUSDT", "COMPUSDT", "DREPUSDT", "RLCUSDT", "BNBUSDT", "TROYUSDT",
    "SPELLUSDT", "KSMUSDT", "VETUSDT", "QNTUSDT", "RAREUSDT", "REQUSDT", "ALICEUSDT", "EGLDUSDT",
    "WANUSDT", "OCEANUSDT", "MAVUSDT", "FDUSDTRY", "ASRUSDT", "JSTUSDT", "PEPEUSDT", "COMBOUSDT",
    "OMGUSDT", "INJUSDT", "BNTUSDT", "BARUSDT", "STORJUSDT", "GBPUSDT", "FISUSDT", "C98USDT",
    "ARPAUSDT", "AXSUSDT", "SOLUSDT", "1000SATSUSDT", "QIUSDT", "CYBERUSDT", "USDCUSDT", "UNFIUSDT",
    "ARUSDT", "PORTOUSDT", "KAVAUSDT", "DCRUSDT", "XNOUSDT", "ASTUSDT", "LOKAUSDT", "USDTUAH",
    "ATOMUSDT", "MLNUSDT", "USDTRUB", "AGIXUSDT", "USDTBIDR", "VICUSDT", "VITEUSDT", "BONDUSDT",
    "POLYXUSDT", "FIOUSDT", "SUIUSDT", "MASKUSDT", "XRPUSDT", "FTMUSDT", "LTOUSDT", "FTTUSDT",
    "WOOUSDT", "MANAUSDT", "BTCUSDT", "BONKUSDT", "BLURUSDT", "ADXUSDT", "ATAUSDT", "BATUSDT",
    "AVAUSDT", "SANDUSDT", "MINAUSDT", "ALPACAUSDT", "SXPUSDT", "ONTUSDT", "ETCUSDT", "BNBDOWNUSDT",
    "NKNUSDT", "CHRUSDT", "CKBUSDT", "SLPUSDT", "LRCUSDT", "USDTPLN",  "REIUSDT", "LUNCUSDT",
    "UMAUSDT", "QKCUSDT", "XLMUSDT", "ARKUSDT", "SUNUSDT", "VOXELUSDT", "YFIUSDT", "BLZUSDT",
    "GALUSDT", "ACMUSDT", "WAXPUSDT", "TFUELUSDT", "SNTUSDT", "OOKIUSDT", "CAKEUSDT", "PROMUSDT",
    "TRUUSDT", "JASMYUSDT", "ROSEUSDT", "USTCUSDT", "DEGOUSDT", "FRONTUSDT", "CTSIUSDT", "PHBUSDT",
    "ILVUSDT", "ETHUSDT", "AMBUSDT", "USDTTRY", "MOBUSDT", "TRBUSDT", "AEURUSDT", "YGGUSDT", "CVPUSDT",
    "XVGUSDT", "BIFIUSDT", "KMDUSDT", "GASUSDT", "ADAUSDT", "PLAUSDT", "AUDIOUSDT", "USDTBRL",
    "TUSDT", "IOSTUSDT", "DEXEUSDT", "ALGOUSDT", "KLAYUSDT", "JTOUSDT", "DODOUSDT", "PENDLEUSDT",
    "BSWUSDT", "APTUSDT", "RPLUSDT", "RIFUSDT", "HOTUSDT", "UFTUSDT", "EOSUSDT", "ZENUSDT", "BTCUPUSDT",
    "ZECUSDT", "GFTUSDT", "STRAXUSDT", "XTZUSDT", "ZILUSDT", "AAVEUSDT", "STMXUSDT", "LUNAUSDT",
    "IDUSDT", "XECUSDT", "ANTUSDT", "AKROUSDT", "AERGOUSDT", "AERGOUSDT", "CITYUSDT", "BURGERUSDT"]

BINANCE_CURRENCY_LIST = [el.replace("USDT", "") for el in BINANCE_USDT_PAIRS_LIST]
